# Site
name: 'Message from the CEO'
description: 'A collection of emails sent by CEOs.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
email: 'b.michael.dick@gmail.com'

include: ["_pages"]
permalink: /:year-:month-:day-:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

     # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]